server:
  port: 2525
  servlet:
    context-path: /contactbook
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: scott
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true;
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
